spring.application.name=student-management-system
server.port=6067

# FIXED: changed sslnode to sslmode
spring.datasource.url=jdbc:postgresql://dpg-d6bsr9h4tr6s73d5k6g0-a.oregon-postgres.render.com:5432/postgressql_f24k?currentSchema=student-management-system&sslmode=require
spring.datasource.username=postgressql_f24k_user
spring.datasource.password=UqgxK2LrpLInFdVifAJmOmUaNiitEbT8
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings
spring.jpa.properties.hibernate.default_schema=student-management-system
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true